apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuberedis.kvstore.name" . }}-secret
  labels:
    {{- include "kuberedis.kvstore.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.kvstore.apiKey | quote }}
