apiVersion: v1
kind: Service
metadata:
  name: kvstore
  namespace: kuberedis
  labels:
    app: kvstore
spec:
  type: ClusterIP
  selector:
    app: kvstore
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
