## Dev environment overrides -- minimal resources, no persistence.

kvstore:
  replicaCount: 1
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

redis:
  replicaCount: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  metrics:
    enabled: false
